/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.layered.view;

import edu.ijse.layered.controller.CustomerController;
import edu.ijse.layered.controller.ItemController;
import edu.ijse.layered.controller.OrderController;
import edu.ijse.layered.dto.CustomerDTO;
import edu.ijse.layered.dto.ItemDTO;
import edu.ijse.layered.dto.OrderDTO;
import edu.ijse.layered.dto.OrderDetailDTO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thisura
 */
public class OrderView extends javax.swing.JFrame {

    /**
     * Creates new form OrderView
     */
    private CustomerController customerController;
    private ItemController itemController;
    private List<OrderDetailDTO> orderDetailDTOs = new ArrayList<>();
    private OrderController orderController;

    public OrderView() {

        customerController = new CustomerController();
        itemController = new ItemController();
        orderController = new OrderController();
        initComponents();

        createTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel2 = new javax.swing.JPanel();
        ManageCustomerPanel2 = new javax.swing.JPanel();
        HeaderLabel2 = new javax.swing.JLabel();
        CustDetailsPanel2 = new javax.swing.JPanel();
        ItemCodeLabel2 = new javax.swing.JLabel();
        OrderIDLabel2 = new javax.swing.JLabel();
        DiscountLabel2 = new javax.swing.JLabel();
        AddItemButton2 = new javax.swing.JButton();
        searchCustomerButton = new javax.swing.JButton();
        orderQty = new javax.swing.JLabel();
        itemCodeText = new javax.swing.JTextField();
        orderIdText = new javax.swing.JTextField();
        discountText = new javax.swing.JTextField();
        orderQtyText = new javax.swing.JTextField();
        CustomerIDLabel = new javax.swing.JLabel();
        customerIdText = new javax.swing.JTextField();
        customerLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        searchItemButton = new javax.swing.JButton();
        ItemLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        UpdateItemButton = new javax.swing.JButton();
        UpdateItemButton1 = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HeaderLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLabel2.setText("ORDER");

        ItemCodeLabel2.setText("Item  ID");

        OrderIDLabel2.setText("Order ID");

        DiscountLabel2.setText("Discount");

        AddItemButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddItemButton2.setText("Add Item");
        AddItemButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemButton2ActionPerformed(evt);
            }
        });

        searchCustomerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchCustomerButton.setText("Search");
        searchCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerButtonActionPerformed(evt);
            }
        });

        orderQty.setText("Quantity ");

        itemCodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeTextActionPerformed(evt);
            }
        });

        orderIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdTextActionPerformed(evt);
            }
        });

        discountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTextActionPerformed(evt);
            }
        });

        orderQtyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderQtyTextActionPerformed(evt);
            }
        });

        CustomerIDLabel.setText("Customer ID");

        customerIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdTextActionPerformed(evt);
            }
        });

        customerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        searchItemButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchItemButton.setText("Search");
        searchItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemButtonActionPerformed(evt);
            }
        });

        ItemLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout CustDetailsPanel2Layout = new javax.swing.GroupLayout(CustDetailsPanel2);
        CustDetailsPanel2.setLayout(CustDetailsPanel2Layout);
        CustDetailsPanel2Layout.setHorizontalGroup(
            CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustDetailsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(orderQty, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CustDetailsPanel2Layout.createSequentialGroup()
                        .addComponent(ItemCodeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustDetailsPanel2Layout.createSequentialGroup()
                                .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchItemButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(CustDetailsPanel2Layout.createSequentialGroup()
                                .addComponent(orderQtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(CustDetailsPanel2Layout.createSequentialGroup()
                        .addComponent(DiscountLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddItemButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustDetailsPanel2Layout.createSequentialGroup()
                        .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderIDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(customerIdText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CustDetailsPanel2Layout.setVerticalGroup(
            CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustDetailsPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderIDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CustomerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(customerIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustDetailsPanel2Layout.createSequentialGroup()
                        .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemCodeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderQty, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderQtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CustDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiscountLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddItemButton2)))
                    .addComponent(ItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        OrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(OrderTable);

        UpdateItemButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateItemButton.setText("Clear");
        UpdateItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateItemButtonActionPerformed(evt);
            }
        });

        UpdateItemButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateItemButton1.setText("PLACE ORDER");
        UpdateItemButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateItemButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageCustomerPanel2Layout = new javax.swing.GroupLayout(ManageCustomerPanel2);
        ManageCustomerPanel2.setLayout(ManageCustomerPanel2Layout);
        ManageCustomerPanel2Layout.setHorizontalGroup(
            ManageCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustDetailsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ManageCustomerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeaderLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageCustomerPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(UpdateItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateItemButton1)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        ManageCustomerPanel2Layout.setVerticalGroup(
            ManageCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageCustomerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManageCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateItemButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BasePanel2Layout = new javax.swing.GroupLayout(BasePanel2);
        BasePanel2.setLayout(BasePanel2Layout);
        BasePanel2Layout.setHorizontalGroup(
            BasePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageCustomerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BasePanel2Layout.setVerticalGroup(
            BasePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanel2Layout.createSequentialGroup()
                .addComponent(ManageCustomerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BasePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BasePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddItemButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemButton2ActionPerformed
        addToTable();
    }//GEN-LAST:event_AddItemButton2ActionPerformed

    private void searchCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerButtonActionPerformed
        searchCustomer();
    }//GEN-LAST:event_searchCustomerButtonActionPerformed

    private void itemCodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeTextActionPerformed

    private void orderIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIdTextActionPerformed

    private void discountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTextActionPerformed

    private void orderQtyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderQtyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderQtyTextActionPerformed

    private void customerIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdTextActionPerformed

    private void searchItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemButtonActionPerformed
        serachItem();
    }//GEN-LAST:event_searchItemButtonActionPerformed

    private void OrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTableMouseClicked

    }//GEN-LAST:event_OrderTableMouseClicked

    private void UpdateItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateItemButtonActionPerformed
        clear();
    }//GEN-LAST:event_UpdateItemButtonActionPerformed

    private void UpdateItemButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateItemButton1ActionPerformed
       placeOrder();
    }//GEN-LAST:event_UpdateItemButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemButton;
    private javax.swing.JButton AddItemButton1;
    private javax.swing.JButton AddItemButton2;
    private javax.swing.JPanel BasePanel;
    private javax.swing.JPanel BasePanel1;
    private javax.swing.JPanel BasePanel2;
    private javax.swing.JPanel CustDetailsPanel;
    private javax.swing.JPanel CustDetailsPanel1;
    private javax.swing.JPanel CustDetailsPanel2;
    private javax.swing.JLabel CustomerIDLabel;
    private javax.swing.JLabel DiscountLabel;
    private javax.swing.JLabel DiscountLabel1;
    private javax.swing.JLabel DiscountLabel2;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JLabel HeaderLabel1;
    private javax.swing.JLabel HeaderLabel2;
    private javax.swing.JLabel ItemCodeLabel;
    private javax.swing.JLabel ItemCodeLabel1;
    private javax.swing.JLabel ItemCodeLabel2;
    private javax.swing.JLabel ItemLabel;
    private javax.swing.JPanel ManageCustomerPanel;
    private javax.swing.JPanel ManageCustomerPanel1;
    private javax.swing.JPanel ManageCustomerPanel2;
    private javax.swing.JLabel OrderIDLabel;
    private javax.swing.JLabel OrderIDLabel1;
    private javax.swing.JLabel OrderIDLabel2;
    private javax.swing.JTable OrderTable;
    private javax.swing.JButton UpdateItemButton;
    private javax.swing.JButton UpdateItemButton1;
    private javax.swing.JTextField customerIdText;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JTextField discountText;
    private javax.swing.JTextField itemCodeText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField orderIdText;
    private javax.swing.JLabel orderQty;
    private javax.swing.JTextField orderQtyText;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JButton searchItemButton;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables

    private void addToTable() {

        OrderDetailDTO dto = new OrderDetailDTO(itemCodeText.getText(),
                Integer.parseInt(orderQtyText.getText()),
                Double.parseDouble(discountText.getText()));

        orderDetailDTOs.add(dto);

        ItemDTO idto;
        
        try {
            idto = itemController.searchItem(dto.getItemID());

            Object[] rowdata = {dto.getItemID(), idto.getItemDescription(), idto.getItemPackSize(), dto.getQuantity(), dto.getDiscount()};

            DefaultTableModel dtm = (DefaultTableModel) OrderTable.getModel();
            dtm.addRow(rowdata);

            clearFields();

        } catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void createTable() {
        String[] columns = {"ItemCode", "Description", "Pack Size", "Quantity", "Discount"};

        DefaultTableModel dtm = new DefaultTableModel(columns, 0);

        OrderTable.setModel(dtm);

    }

    private void searchCustomer() {
        try {
            String CustID = customerIdText.getText();
            CustomerDTO cdto = customerController.searchCustomer(CustID);

            customerLabel.setText(cdto.getCustTitle() + " " + cdto.getCustName() + " | RS. " + cdto.getCustSalary().toString() + " | " + cdto.getCustAddress() + ", " + cdto.getCustCity());
        } catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void serachItem() {
        try {
            String ItemCode = itemCodeText.getText();
            ItemDTO idto = itemController.searchItem(ItemCode);

            ItemLabel.setText(idto.getItemDescription() + " | Pack Size - " + idto.getItemPackSize() + " | QOH - " + idto.getItemQty() + " | Price - RS. " + idto.getItemUnitPrice());
        } catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void placeOrder() {
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        OrderDTO dto = new OrderDTO(orderIdText.getText(), 
                customerIdText.getText(), 
                sdf.format(new Date()), 
                orderDetailDTOs);
        
        try {
            String resp = orderController.placeOrder(dto);
            JOptionPane.showConfirmDialog(this, resp);
        } catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void clearFields() {
        itemCodeText.setText("");
        orderQtyText.setText("");
        discountText.setText("");
    }

    private void clear() {
        orderDetailDTOs = new ArrayList<>();
        createTable();
        clearFields();
        
    }
}
